version: "3.7"

services:
  toggledb:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: dummypassword
      POSTGRES_USER: dummyuser
      POSTGRES_DB: unleash
    networks: 
      - database
  toggleserver:
    build: .
    ports:
      - 4242:4242
    depends_on:
      - toggledb
    networks: 
      - database

networks: 
  database: